name: Tygrus
favicon: null
layout_spectrum: 0.62602
typography_spectrum: 0.59162
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c1151'
    - '#4e9fa0'
    - '#c5dadb'
    - '#1b3e66'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.6345656379126012
purpose: []
